WITH SALES_BY_CATEGORY AS (
    SELECT CATEGORY, SALES
    FROM BOOK
             JOIN BOOK_SALES
                  ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
    WHERE year(SALES_DATE) = 2022 and month(SALES_DATE) = 1
)

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM SALES_BY_CATEGORY
GROUP BY CATEGORY
ORDER BY CATEGORY
